# Generated by Django 4.0.1 on 2022-01-27 03:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(verbose_name=builtins.max)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
