# Generated by Django 4.0.1 on 2022-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_berita_tumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tumbnail',
            field=models.ImageField(default='default.png', upload_to='berita'),
        ),
    ]
