# Generated by Django 4.0.1 on 2022-01-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_rename_pertanyan_choice_pertanyaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='pertanyaan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.question'),
        ),
    ]
